<?php 
require_once __DIR__ . '/../models/movie_db.php';
require_once __DIR__ . '/../models/showtime_db.php';
?>
<main class="schedule-main">
    <div class="schedule-container">
        <!-- Date Filter -->
        <section class="date-filter">
            <h3 class="section-title">Chọn ngày chiếu</h3>
            <div class="date-slider" id="dateSlider">
                <!-- Dates will be generated by JavaScript -->
            </div>
        </section>

        <!-- Movie Schedule -->
        <section class="movie-schedule">
            <div class="schedule-header">
                <h2>Chọn lịch chiếu</h2>
                <div class="filter-buttons">
                    <button class="filter-btn active" data-filter="all">
                        <i class="fas fa-th"></i> Tất cả
                    </button>
                    <button class="filter-btn" data-filter="2D">
                        <i class="fas fa-film"></i> 2D
                    </button>
                    <button class="filter-btn" data-filter="3D">
                        <i class="fas fa-glasses"></i> 3D
                    </button>
                </div>
            </div>

            <div class="movies-list" id="moviesList">
                <!-- Movies will be loaded here by JavaScript -->
                <div class="loading">
                    <i class="fas fa-spinner fa-spin"></i>
                    <p>Đang tải lịch chiếu...</p>
                </div>
            </div>
        </section>
    </div>
</main>

<script src="/src/js/schedule.js"></script>
